name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Replace environment variables
        run: |
          sed -i "s|apiKey: ''|apiKey: '${{ secrets.FIREBASE_API_KEY }}'|g" src/environments/environment.ts
          sed -i "s|authDomain: ''|authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'|g" src/environments/environment.ts
          sed -i "s|projectId: ''|projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'|g" src/environments/environment.ts
          sed -i "s|storageBucket: ''|storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'|g" src/environments/environment.ts
          sed -i "s|messagingSenderId: ''|messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'|g" src/environments/environment.ts
          sed -i "s|appId: ''|appId: '${{ secrets.FIREBASE_APP_ID }}'|g" src/environments/environment.ts

      - name: Build Angular app
        run: ng build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
